### ISSUE TITLE
Could not run nuclei: no templates provided for scan

### ISSUE THREAD

**Issue by EmptyZeroRain** [projectdiscovery/fuzzing-templates#39]
I downloaded fuzzing templates through git, and then I specified templates using the nuclei - t parameter. Then, I used u to specify the domain name, which prompted an error
<img width="556" alt="image" src="https://github.com/projectdiscovery/fuzzing-templates/assets/48972652/48e35745-4213-4ef3-a0cc-3180b00686a5">
<img width="994" alt="image" src="https://github.com/projectdiscovery/fuzzing-templates/assets/48972652/0dad1873-ce4c-469f-8a58-59f6d7c6a163">
Refer to execution on github

**Comment by princechaddha** [comment]
Hi @EmptyZeroRain, have you tried providing a full path to the templates using -t? Is it working? Also, can you try using `-itags fuzz`? The fuzzing templates are not run during the default scan.

**Comment by ehsandeep** [comment]
@EmptyZeroRain it was an issue with template loading in nuclei v3 release, now fixed in latest releae - https://github.com/projectdiscovery/nuclei/releases/tag/v3.0.2
