### ISSUE TITLE
Could not run nuclei: no templates provided for scan 

### ISSUE THREAD

**Issue by amit123jain** [projectdiscovery/fuzzing-templates#43]
**Issue description:**
When running the [fuzzing-templates](https://github.com/projectdiscovery/fuzzing-templates) on testphp.vulnweb.com or any website.

**Error:**

[FTL] Could not run nuclei: no valid templates were found

**Command:**
cat testphp.vulnweb.com-urls.txt | nuclei -t ~/fuzzing-templates -tags redirect
nuclei -list testphp.vulnweb.com-urls.txt -t  ~/fuzzing-templates -tags redirect

**Screenshot:**

![error](https://github.com/projectdiscovery/fuzzing-templates/assets/22009238/a1b8da6a-16aa-4ff7-bed8-2a36dfb8707d)

**Comment by dogancanbakir** [comment]
See https://github.com/projectdiscovery/nuclei/issues/3885 for the solution.

**Comment by rootd4ddy** [comment]
This is still an issue for me. 

```
nuclei -l sqli.txt -t /home/r00tdaddy/nuclei-templates/fuzzing-templates/ -itags fuzz

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.3

                projectdiscovery.io

[ERR] Could not find template '/home/user/nuclei-templates/fuzzing-templates/sqli/error-based.yaml': could not find file: stat /home/r00tdaddy/nuclei-templates/fuzzing-templates: no such file or directory
[WRN] Found 1 template[s] loaded with deprecated paths, update before v3 for continued support.
[INF] Current nuclei version: v3.2.3 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] Targets loaded for current scan: 869
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

Using current nuclei version and added the -itags fuzz flag but its not working.

**Comment by amit123jain** [comment]
**I try this:** https://github.com/projectdiscovery/nuclei/issues/3885

**but results as same:-** Could not run nuclei: no templates provided for scan
